export const sample = {
  id: "sample-x",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 640,
        top: 360,
        originX: "center",
        originY: "center",
        width: 1280,
        height: 720,
        fill: "#0B1220",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Rect",
        left: 640,
        top: 360,
        originX: "center",
        originY: "center",
        width: 1280,
        height: 720,
        fill: "#0EA5E90F",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Rect",
        left: 92,
        top: 82,
        originX: "left",
        originY: "top",
        width: 8,
        height: 64,
        fill: "#38BDF8",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Textbox",
        left: 120,
        top: 72,
        originX: "left",
        originY: "top",
        width: 760,
        height: 90,
        fill: "#EAF2FF",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "지구 온난화의 영향",
        fontSize: 56,
        fontFamily: "Helvetica",
        fontWeight: "bold",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Textbox",
        left: 120,
        top: 154,
        originX: "left",
        originY: "top",
        width: 760,
        height: 40,
        fill: "#A9B7D0",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "빙하 감소와 서식지 변화가 생태계와 해수면에 미치는 영향",
        fontSize: 22,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Rect",
        left: 92,
        top: 232,
        originX: "left",
        originY: "top",
        width: 580,
        height: 408,
        fill: "#0F1B33",
        stroke: "#20304E",
        strokeWidth: 2,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Textbox",
        left: 124,
        top: 262,
        originX: "left",
        originY: "top",
        width: 520,
        height: 56,
        fill: "#EAF2FF",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "주요 영향",
        fontSize: 30,
        fontFamily: "Helvetica",
        fontWeight: "bold",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Circle",
        left: 132,
        top: 338,
        originX: "center",
        originY: "center",
        width: 12,
        height: 12,
        fill: "#38BDF8",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 6,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Textbox",
        left: 152,
        top: 322,
        originX: "left",
        originY: "top",
        width: 500,
        height: 70,
        fill: "#D7E4FA",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "해수면 상승\n• 연안 침수·염수 침투 위험 증가",
        fontSize: 24,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Circle",
        left: 132,
        top: 430,
        originX: "center",
        originY: "center",
        width: 12,
        height: 12,
        fill: "#38BDF8",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 6,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Textbox",
        left: 152,
        top: 414,
        originX: "left",
        originY: "top",
        width: 500,
        height: 60,
        fill: "#D7E4FA",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "극지 생태계 붕괴\n• 해빙 감소로 북극곰 먹이·이동 경로 변화",
        fontSize: 24,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Circle",
        left: 132,
        top: 522,
        originX: "center",
        originY: "center",
        width: 12,
        height: 12,
        fill: "#38BDF8",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 6,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Textbox",
        left: 152,
        top: 506,
        originX: "left",
        originY: "top",
        width: 500,
        height: 60,
        fill: "#D7E4FA",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "기후 극한 현상 증가\n• 폭염·가뭄·폭우의 빈도와 강도 확대",
        fontSize: 24,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Rect",
        left: 720,
        top: 232,
        originX: "left",
        originY: "top",
        width: 468,
        height: 408,
        fill: "#0F1B33",
        stroke: "#20304E",
        strokeWidth: 2,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 18,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Image",
        left: 954,
        top: 388,
        originX: "center",
        originY: "center",
        width: 440,
        height: 308,
        fill: "#00000000",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "anonymous",
        data: {
          imagePrompt:
            "Photorealistic Arctic scene, wide composition: a melting glacier with visible cracks and blue ice, floating ice chunks on dark cold water, overcast sky with soft diffused light. On a small ice floe in the foreground stands a lone polar bear (adult), looking slightly toward camera, conveying vulnerability. Cool color palette (icy blues, whites, slate gray). High resolution, documentary style, no text, no logo.",
          isPlaceholder: true,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Rect",
        left: 744,
        top: 520,
        originX: "left",
        originY: "top",
        width: 420,
        height: 96,
        fill: "#0B1220CC",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 14,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Textbox",
        left: 764,
        top: 540,
        originX: "left",
        originY: "top",
        width: 380,
        height: 70,
        fill: "#EAF2FF",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "빙하 융해 → 해수면 상승\n서식지 감소 → 생물다양성 위협",
        fontSize: 22,
        fontFamily: "Helvetica",
        fontWeight: "bold",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
      {
        type: "Line",
        left: 0,
        top: 0,
        originX: "left",
        originY: "top",
        width: 0,
        height: 0,
        fill: "#00000000",
        stroke: "#20304E",
        strokeWidth: 1,
        text: "",
        fontSize: 0,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: 92,
        x2: 1188,
        y1: 668,
        y2: 668,
      },
      {
        type: "Textbox",
        left: 92,
        top: 678,
        originX: "left",
        originY: "top",
        width: 520,
        height: 28,
        fill: "#7F93B4",
        stroke: "#00000000",
        strokeWidth: 0,
        text: "슬라이드 1",
        fontSize: 16,
        fontFamily: "Helvetica",
        fontWeight: "normal",
        textAlign: "left",
        opacity: 1,
        angle: 0,
        scaleX: 1,
        scaleY: 1,
        radius: 0,
        src: "",
        crossOrigin: "",
        data: {
          imagePrompt: "",
          isPlaceholder: false,
        },
        x1: null,
        x2: null,
        y1: null,
        y2: null,
      },
    ],
    background: "#0B1220",
  },
  prompt: "지구 온난화의 영향",
};
