export const sample = [
  {
    id: "sample-x",
    fabricJson: {
      version: "7.0.0",
      background: "#ffffff",
      objects: {
        objects: [
          {
            type: "Textbox",
            left: 640,
            top: 100,
            originX: "center",
            originY: "top",
            width: 800,
            height: 40,
            fill: "#000000",
            text: "Upstage 모델 소개",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "center",
            opacity: 1,
          },
          {
            type: "Textbox",
            left: 640,
            top: 180,
            originX: "center",
            originY: "top",
            width: 800,
            height: 30,
            fill: "#333333",
            text: "기업 소개 & Solar Pro 2 핵심 목표",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "center",
            opacity: 1,
          },
          {
            type: "Image",
            left: 200,
            top: 300,
            originX: "left",
            originY: "top",
            width: 800,
            height: 400,
            src: "",
            data: {
              imagePrompt:
                "Upstage corporate logo with modern design, clean lines, blue and white colors",
              isPlaceholder: true,
              iconName: "",
              iconColor: "",
              isIcon: false,
            },
          },
        ],
      },
    },
    prompt: "Upstage 모델 소개",
  },
  {
    id: "sample-y",
    prompt: "Upstage 모델 소개2",
    fabricJson: {
      version: "7.0.0",
      background: "#ffffff",
      objects: {
        objects: [
          {
            type: "Textbox",
            left: 60,
            top: 60,
            width: 1160,
            height: 36,
            text: "핵심 기능 및 차별점",
            fontFamily: "Arial",
            fontWeight: "bold",
            textAlign: "left",
            opacity: 1,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "lightning",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
          {
            type: "Textbox",
            left: 60,
            top: 150,
            width: 100,
            height: 22,
            text: "1. 대규모 언어 처리",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "left",
            opacity: 1,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "target",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
          {
            type: "Textbox",
            left: 200,
            top: 150,
            width: 300,
            height: 22,
            text: "초대규모 언어 모델 기반",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "left",
            opacity: 1,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "lightning",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
          {
            type: "Textbox",
            left: 60,
            top: 220,
            width: 100,
            height: 22,
            text: "2. 구조화 문서 이해",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "left",
            opacity: 1,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "target",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
          {
            type: "Textbox",
            left: 200,
            top: 220,
            width: 300,
            height: 22,
            text: "문서 구조 자동 분석",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "left",
            opacity: 1,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "target",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
          {
            type: "Textbox",
            left: 60,
            top: 290,
            width: 100,
            height: 22,
            text: "3. 실시간 번역",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "left",
            opacity: 1,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "clock",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
          {
            type: "Textbox",
            left: 200,
            top: 290,
            width: 300,
            height: 22,
            text: "지연 없는 즉시 번역",
            fontFamily: "Arial",
            fontWeight: "normal",
            textAlign: "left",
            opacity: 1,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "clock",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
          {
            type: "Rect",
            left: 60,
            top: 120,
            width: 1160,
            height: 60,
            fill: "#e0e0e0",
            opacity: 0.3,
            angle: 0,
            data: {
              imagePrompt: "",
              isPlaceholder: false,
              iconName: "target",
              iconColor: "#FF6B00",
              isIcon: true,
            },
          },
        ],
      },
    },
  },
];
